name: bot
description: The PPTOS Archive Bot.
version: 0.1.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  dotenv: ^4.0.1
  html: ^0.15.1
  nyxx: ^4.4.0
  nyxx_interactions: ^4.5.0
  process_run: ^0.12.5+2
